{% set version = '0.39' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-admisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/admisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/admisc/admisc_{{ version }}.tar.gz
  sha256: 153afa8dd3fc52fff73105e0d8877a866f7c2124ca01d3dfdae070ed7f4e21cc

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('admisc')"           # [not win]
    - "\"%R%\" -e \"library('admisc')\""  # [win]

about:
  home: https://github.com/dusadrian/admisc
  license: GPL-3.0-only
  summary: |
    Contains functions used across packages 'DDIwR', 'QCA' and 'venn'. Interprets and
    translates, factorizes and negates SOP - Sum of Products expressions, for both binary
    and multi-value crisp sets, and extracts information (set names, set values) from
    those expressions. Other functions perform various other checks if possibly numeric
    (even if all numbers reside in a character vector) and coerce to numeric, or check
    if the numbers are whole. It also offers, among many others, a highly versatile
    recoding routine and some more flexible alternatives to the base functions 'with()'
    and 'within()'. SOP simplification functions in this package use related minimization
    from package 'QCA', which is recommended to be installed despite not being listed
    in the Imports field, due to circular dependency issues.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: admisc
# Version: 0.39
# Title: Adrian Dusa's Miscellaneous
# Authors@R: person( given = "Adrian", family = "Dusa", role = c("aut", "cre", "cph"), email = "dusa.adrian@unibuc.ro", comment = c(ORCID = "0000-0002-3525-9253"))
# Depends: R (>= 3.5.0)
# Imports: methods
# Suggests: QCA (>= 3.7)
# Description: Contains functions used across packages 'DDIwR', 'QCA' and 'venn'. Interprets and translates, factorizes and negates SOP - Sum of Products expressions, for both binary and multi-value crisp sets, and extracts information (set names, set values) from those expressions. Other functions perform various other checks if possibly numeric (even if all numbers reside in a character vector) and coerce to numeric, or check if the numbers are whole. It also offers, among many others, a highly versatile recoding routine and some more flexible alternatives to the base functions 'with()' and 'within()'. SOP simplification functions in this package use related minimization from package 'QCA', which is recommended to be installed despite not being listed in the Imports field, due to circular dependency issues.
# License: GPL (>= 3)
# URL: https://github.com/dusadrian/admisc
# BugReports: https://github.com/dusadrian/admisc/issues
# NeedsCompilation: yes
# Packaged: 2025-10-31 16:52:48 UTC; dusadrian
# Author: Adrian Dusa [aut, cre, cph] (ORCID: <https://orcid.org/0000-0002-3525-9253>)
# Maintainer: Adrian Dusa <dusa.adrian@unibuc.ro>
# Repository: CRAN
# Date/Publication: 2025-11-02 06:10:57 UTC
